With an aim to write our own `Embedding` model used in the previous models, we first delve more into registration of parameters with PyTorch; how to do it, and what is its significance.

When we initialize/assign `tensor`s to an attribute, they are not automatically registered as a parameter of the model. Note that we query parameters with `model_instance.parameters()`.

In [1]:
from fastai.tabular.all import *

class T(Module):
    def __init__(self):
        self.a = torch.ones(3)

L(T().parameters())

(#0) []

To do so we wrap the objects to be registered in `nn.Parameter`.

In [2]:
class T(Module):
    def __init__(self):
        self.a = nn.Parameter(torch.ones(3))

L(T().parameters())

(#1) [Parameter containing:
tensor([1., 1., 1.], requires_grad=True)]

At this point one wonders why we hadn't needed to do this when we assigned submodules `Embedding` in our `DotProduct`. Of course, `Embedding` is not a `tensor`. Rather, predefined PyTorch modules already register their relevant parameters. We illustrate thes below.

Of course, such predefined modules may make use of additional (unregistered) tensors and state e.g. for hyperparameters and caching.

In [3]:
class T(Module):
    def __init__(self):
        self.a = nn.Linear(1, 3)

t = T()
L(t.parameters())


(#2) [Parameter containing:
tensor([[-0.0827],
        [ 0.9234],
        [ 0.4008]], requires_grad=True),Parameter containing:
tensor([-0.0371, -0.9097, -0.7345], requires_grad=True)]

The predefined `Linear` layer stores its model weights in its `weight` attribute.

In [4]:
type(t.a.weight)

torch.nn.parameter.Parameter

The primary significance of registering parameters with PyTorch is that PyTorch will perform automatic differention on it when training.